services:
    frankenphp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4431:443"
            - "4431:443/udp"
            - "801:80"
        volumes:
            - .:/app
        restart: unless-stopped
