services:
    frankenphp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "801:80"
            - "4431:443"
        volumes:
            - stupid-inventory-storage:/app/storage
            - stupid-inventory-db:/app/database
        restart: unless-stopped

volumes:
    stupid-inventory-storage:
    stupid-inventory-db:
