services:
  php:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - '9000:8000'
      - '8080:8080'
      - '8443:8443'
    environment:
      PHP_FPM_POOL_NAME: "easy-inventory_php"
      PHP_OPCACHE_ENABLE: 1
      SSL_MODE: "mix"
      AUTORUN_ENABLED: "false"
    volumes:
      - .:/var/www/html
#    networks:
#      - sail
#    depends_on:
#      - mysql
#  mysql:
#    image: 'mysql/mysql-server:8.0'
#    ports:
#      - '${FORWARD_DB_PORT:-3306}:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_DATABASE: '${DB_DATABASE}'
#      MYSQL_USER: '${DB_USERNAME}'
#      MYSQL_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    volumes:
#      - 'sail-mysql:/var/lib/mysql'
#    networks:
#      - sail
#    healthcheck:
#      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
#      retries: 3
#      timeout: 5s
#
#  queue:
#    image: serversideup/php:8.3-fpm-nginx
#    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
#    environment:
#      PHP_FPM_POOL_NAME: "my-app_queue"
#    volumes:
#      - .:/var/www/html
#
#  task:
#    image: serversideup/php:8.3-fpm-nginx
#    command: ["php", "/var/www/html/artisan", "schedule:work"]
#    environment:
#      PHP_FPM_POOL_NAME: "my-app_task"
#    volumes:
#      - .:/var/www/html


#
#networks:
#  sail:
#    driver: bridge
#volumes:
#  sail-mysql:
#    driver: local

